// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package leftoverfoods

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Business struct {
	BusinessID int32
	Username   pgtype.Text
	Name       pgtype.Text
	Category   pgtype.Text
	StreetName pgtype.Text
	City       pgtype.Text
	Country    pgtype.Text
	ZipCode    pgtype.Text
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type User struct {
	UserID       int32
	Username     pgtype.Text
	FirstName    pgtype.Text
	LastName     pgtype.Text
	StreetName   pgtype.Text
	City         pgtype.Text
	Country      pgtype.Text
	ZipCode      pgtype.Text
	EmailAddress pgtype.Text
	Currency     pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
