// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package leftoverfoods

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username, first_name, last_name,country, email_address
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING user_id, username, first_name, last_name, street_name, city, country, zip_code, email_address, currency, created_at, updated_at
`

type CreateUserParams struct {
	Username     pgtype.Text
	FirstName    pgtype.Text
	LastName     pgtype.Text
	Country      pgtype.Text
	EmailAddress pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.Country,
		arg.EmailAddress,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.StreetName,
		&i.City,
		&i.Country,
		&i.ZipCode,
		&i.EmailAddress,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT user_id, username, first_name, last_name, street_name, city, country, zip_code, email_address, currency, created_at, updated_at FROM users
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, userID int32) (User, error) {
	row := q.db.QueryRow(ctx, getUser, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.StreetName,
		&i.City,
		&i.Country,
		&i.ZipCode,
		&i.EmailAddress,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listbBusines = `-- name: ListbBusines :many
SELECT business_id, username, name, category, street_name, city, country, zip_code, created_at, updated_at FROM business
ORDER BY name
`

func (q *Queries) ListbBusines(ctx context.Context) ([]Business, error) {
	rows, err := q.db.Query(ctx, listbBusines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Business
	for rows.Next() {
		var i Business
		if err := rows.Scan(
			&i.BusinessID,
			&i.Username,
			&i.Name,
			&i.Category,
			&i.StreetName,
			&i.City,
			&i.Country,
			&i.ZipCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
